### ISSUE TITLE
[Issue] Cannot run from keybind

### ISSUE THREAD

**Issue by jpmvferreira** [muquit/grabc#5]
Trying to use this tool as a key combination from i3 fails.

Here's the line in my i3 config:
`bindsym $mod+c exec "/usr/bin/grabc | xclip -r -selection clipboard"`
However when trying to paste, it comes out empty.

If i change it to output to a file such as:
`bindsym $mod+c exec "/usr/bin/grabc > ~/test.txt`
The file is create but no content is in it.

After pressing the key combination, using htop to check for processes show that there is no instance of grabc running, which means it's exiting instantly for some reason and outputting nothing to the file `test.txt`.

Using `grabc -d` also gives nothing in the same `test.txt` file.

Other tools being run exactly the same way within my i3 config have worked as expected so far.

**Comment by muquit** [comment]
I can not reproduce it on Ubuntu 19.04 with i3. Only thing I can suggest is to compile it yourself,
put debug messages and see where the issue is. Thanks.

Here is my session

```
$ cat /etc/issue
Ubuntu 19.04 \n \l

$ ./grabc -h

grabc v1.0.2
A program to identify a pixel color of an X Window
by muquit@muquit.com https://www.muquit.com/

Usage: grabc [options]
Where the options are:
 -v      - show version info
 -h      - show this usage
 -hex    - print pixel value as Hex on stdout
 -rgb    - print pixel value as RGB on stderr
 -W      - print the Window id at mouse click
 -w id   - window id in hex, use -l +x+y
 -l +x+y - pixel co-ordinate. requires window id
 -d      - show debug messages
 -a      - Print all 16 bits RGB components of color
           Default is high order 8 bits of components
Example:
* Print pixel color in hex on stdout:
   $ grabc
* Show usage:
   $ grabc -h
* Print Window Id (Note the upper case W):
   $ grabc -W
* Print pixel color of Window iwith id 0x13234 at location 10,20
   $ grabc -w 0x13234 -l +10+20

$ ./grabc -d |xclip -r -selection clipboard
[Debug]:   Root Window Id: 0x00000143
[Debug]: Target Window Id: 0x00c00006  X,Y: +461+641
[Debug]: Color: #3b297f

Right click mouse + paste
#3b297f
```

**Comment by jpmvferreira** [comment]
So you're saying if you have `bindsym $mod+c exec "/usr/bin/grabc | xclip -r -selection clipboard"` in your i3 config and hit `$mod+c` the cursor changes shape, and you get the hex value of that same pixel in your clipboard? That's strange, i'm not sure why is it not working with me tho, even with the `-d` flag.

I guess ill try to compile it then.

**Comment by jpmvferreira** [comment]
Probably should have mentioned, i'm using the `grabc` package from the AUR, using the `grabc-git` also has the same result.

**Comment by jpmvferreira** [comment]
Compiling it using `make -d` yields the same result.

Here's the output of that same command: https://termbin.com/tr1k

**Comment by muquit** [comment]
Question is are you using grabc v1.0.2? Lot of distributions include old version of grabc.

**Comment by jpmvferreira** [comment]
Yes, it's 1.0.2.

Here's the AUR page of both of them:
https://aur.archlinux.org/packages/grabc/
https://aur.archlinux.org/packages/grabc-git/

Issue still persist on both.

**Comment by muquit** [comment]
How about compiling and running in debug to see what's going on? I suspect it is probably crashing probably due to depth of display etc.

```
$ make
$ ./grabc -d
```

and see where it is bailing or crashing.

Thanks

**Comment by jpmvferreira** [comment]
i don't think i'm making myself clear, running it from the command line works as expected, however running it from within my i3 config doesn't output any result.

I've just compiled it by myself, and added this to my i3 config:
`bindsym $mod+c "exec ~/temp/grabc/grabc -d >> ~/temp/grabc/log.txt & notify-send 'random not'"`

When pressing `$mod+c` the notification instantly shows up, and the file `log.txt` is empty.

Running `./grabc -d` from my terminal emulator works as expected and isn't crashing.

**Comment by muquit** [comment]
Sorry I misunderstood your problem, I thought grabc was not working. What's happening is: the way i3 ran grabc, grabc could not grab the mouse pointer. Specify ```--release``` with bindsym and it will work.

Thanks.

**Comment by jpmvferreira** [comment]
Yes that's it, i figured it might be the way i3 operated, didn't know that there were such a feature as `--release`, thanks for the help!
